### ISSUE TITLE
Who's working on which translation.

### ISSUE THREAD

**Issue by remybach** [confcodeofconduct/confcodeofconduct.com#1]
Completed Translations:

German - @skade 
Italian - @lantiga 
Norwegian - @cwattengard
Spanish - @martuishere 
Dutch - @dvberkel 

Awaiting proof and sign off:

Afrikaans - @remybach
Danish - @joakimkejser 
Finnish - @clooth
French - @gleu
Greek - @Zorbash
Polish - @kamilogorek

**Comment by Erithair** [comment]
I'm working on the Simplified Chinese translation.

**Comment by PontusHorn** [comment]
Doing a Swedish translation.

**Comment by dougwyu** [comment]
> I'm working on the Simplified Chinese translation.

is the Simplified Chinese translation available?  I don't see it.  We can do one.

**Comment by erithair** [comment]
> > I'm working on the Simplified Chinese translation.
> 
> is the Simplified Chinese translation available? I don't see it. We can do one.

@dougwyu I've made a PR #77 for Simplified Chinese. It should be ready once I finish all improvements suggested by the review.

**Comment by MattiSG** [comment]
@dougwyu since @erithair seems to find it hard to find time to push #77 forward, if you feel like handling #77's review comments please do so! You can fork #77 and open a new PR with improvements taken in 🙂

**Comment by MattiSG** [comment]
This issue being more of a listing than an actual _issue_ (i.e. I don't know when it would be closed), I'm going forward and closing it.

If you want to contribute a new translation or improve an existing one, please have a look at the open PRs if one is already there, please review the languages you can; if there are none, feel free to submit a PR with your contribution! 😃
