### ISSUE TITLE
Serve over HTTPS

### ISSUE THREAD

**Issue by mnot** [confcodeofconduct/confcodeofconduct.com#104]
It'd be great if this were available over HTTPS, and even better if it redirected there from HTTP and locked it in with HSTS.

**Comment by remy** [comment]
We'd have to move off heroku for hosting (as they charge silly for https)
and get some letsencrypt certs. Ideas?

**Comment by stevejalim** [comment]
Heroku's SSL endpoints are now free (hurrah) and https://github.com/substrakt/letsencrypt-heroku should make the transition easier

**Comment by rmaclean-ee** [comment]
Why not use cloudflare for this? They offer a free HTTPS solution which has scaled really well for the projects I have used and is independent of the hosting provider.

**Comment by MattiSG** [comment]
@rmaclean-ee do you want to set this up? 🙂

**Comment by rmaclean** [comment]
Very happy to help with this.

I need your email (and any other admins) so I can add you to the cloudflare account I setup.

I have done the basic setup in CloudFlare, the next steps are to change the DNS:
`ns1.dnsimple.com` to `hans.ns.cloudflare.com`
`ns2.dnsimple.com` to `nora.ns.cloudflare.com`
 (the other DNS can be removed)

You can `nslookup `against those servers to confirm the setting are right. The only issue it could find is there are no MX records, so if there was/is email we just need to figure that out.



(sorry for the delay, been swamped but things are good now - also using my personal account which is more appropriate)

**Comment by MattiSG** [comment]
@remy @janl can you handle that? If not (or if it feels more appropriate in all cases considering the last two years), can you hand over DNS and hosting management to me? 🙂

**Comment by remy** [comment]
Late reply, but I moved to netlify so this is done.
