### ISSUE TITLE
Profanity in the Dutch version

### ISSUE THREAD

**Issue by raboof** [confcodeofconduct/confcodeofconduct.com#107]
Could someone please take a look at #67 ?

The current Dutch text literally translates to "Don't be a dickhead", I'm proposing "Treat each other excellently" as the alternative.

**Comment by remy** [comment]
It might actually be worth removing the line entirely, we've removed it from the en-gb copy in the last 6 months based on feedback.

WDYT?

**Comment by raboof** [comment]
Sounds just fine to me!
