### ISSUE TITLE
Should I, as a Another White Dude, have access to this repo?

### ISSUE THREAD

**Issue by remy** [confcodeofconduct/confcodeofconduct.com#116]
I've been thinking about this over the last few days: I'm another white dude, and I have access to this repo (and manage releasing it to the server). I kinda doesn't sit right in my head.

The biggest issue I (think I) see is that new issues are raised, and they're not being handled properly by me (partly because my time is split amongst client work, family and lot of side work, but **mostly** because I don't have the experience or insight).

On one hand, I think I should be replaced (entirely) by one or many "non-white-dudes" (and also do some work to automate deploying - which is easier these days). 

On the other hand, as terrible as this is, I'm in a privileged position where I'm not (or very very rarely) met with abuse for my decisions. So if I merge a PR that upsets some other "white-dude" it's not typically much of an issue. [this reads horribly, but trying to be open].

Caveats: I'm using "white-dude" as a rather vague statement about people who are like me: white, western, access to money, technology, etc — privileged.

My preferred outcome: I'm replaced with one or two (or more) people with an existing track record in diversity, conferences, org, etc.

Open to discussion. 

One thing I would ask: please don't volunteer someone without their permission first.

**Comment by jennschiffer** [comment]
i don't see the harm in you being involved–a coc is not *only* for "non-white-dudes" so your representation does matter. in the case that you feel like you want more diversity in the collaborator role, then advertise that.

**Comment by remy** [comment]
@jennschiffer Good point, and I'll raise a new issue that does exactly that.

For me, it's that I'm concerned that I'm not qualified to be a gatekeeper of the PRs right now. Which, if I guess if we're able to increase (or rather actually "have") diversity of collaborators on this repo _and_ I get auto deploying working, then that problem solves itself.
