### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by MattiSG** [confcodeofconduct/confcodeofconduct.com#129]
## Rationale

As seen in #75 and #6, credit seems important. There is also an obvious need of allowing reuse, which #128 tried to solve. So we do need to add a license to this repo (duh!).

## Problem

The current `README` by @remy currently states that this is a “public resource”, and #6 states that the original would be [the Ada initiative](http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Policy). This does indeed look the same, but I guess any two anti-harassment conference policies could look similar  :wink:

So I would like an authoritative validation of ancestry: @remy, can you please confirm that the original content could be licensed as a public domain, CC0 work, and trace its ancestry as much as possible?

## Translations

As for the translation authors, it would be quite long and possibly unfruitful to wait for their explicit confirmation. Once we've cleared that CC0 is a valid base, I will mention them all and try to get explicit approval from as many as possible, but will also add a timebox after which I will assume that they agree with the licensing. If one does not agree later on, s·he will be able to remove her work from the site.

An alternative could be to allow for language-specific licensing, but I'm afraid this would become quite complex. We'll see what happens if several translators raise issues.

**Comment by remy** [comment]
@MattiSG happy to take your lead. The links in the footer of the page are exactly where it was sourced from.
