### ISSUE TITLE
Using the "race" word seems wrong for a CoC

### ISSUE THREAD

**Issue by sinedied** [confcodeofconduct/confcodeofconduct.com#146]
The word "race" to designate different ethnicities is outdated and irrelevant nowadays, and I was especially shocked to see it used for a CoC.

The current scientific consensus says that all humans belong to the same species, and the race term only applies to animal categorization (you can read [Wikipedia](https://en.wikipedia.org/wiki/Race_(human_categorization)) for sourced info on the subject).

I would advocate to remove this word entirely, as the (already used) word "ethnicity" is a less ambiguous way to convey a similar meaning.

I'm willing to propose a PR for this change on English and French versions (only languages I'm fluent in), but wanted to open the discussion for it first.

**Comment by MattiSG** [comment]
Happy to see a PR in that direction.

**Comment by MattiSG** [comment]
Discussion moved to #149.
