### ISSUE TITLE
Deploys failing in CI tests

### ISSUE THREAD

**Issue by PBartrina** [confcodeofconduct/confcodeofconduct.com#172]
I am unable to pass the tests in [this PR](https://github.com/confcodeofconduct/confcodeofconduct.com/pull/171) due to the deprecation of the ubuntu used.
As shown in the log:

```5:35:53 PM: Build ready to start
5:35:53 PM: ---------------------------------------------------------------------  
UNSUPPORTED BUILD IMAGE  

The build image for this site uses Ubuntu 14.04 Trusty Tahr, which is no longer supported.  

To enable builds for this site, select a later build image at the following link:  
https://app.netlify.com/sites/confcodeofconduct/settings/deploys#build-image-selection  

For more details, visit the build image migration guide:  
https://answers.netlify.com/t/end-of-support-for-trusty-build-image-everything-you-need-to-know/39004  
---------------------------------------------------------------------```

**Comment by remy** [comment]
I'll get that sorted out.

**Comment by MattiSG** [comment]
Hey @remy, checking in to avoid duplicate work. Are you working on this? 🙂

**Comment by remy** [comment]
@MattiSG I updated the image a few days ago on netlify, so it should be deploying previews and merges correctly again. I just triggered a deploy on that latest PR just to be sure though.

**Comment by MattiSG** [comment]
I don't know if this is a consequence of the issue listed here or if a manual action has to be taken, but after merging #171, https://ca.confcodeofconduct.com still yields a 404. I did not receive any notification from GitHub of a failed process.

@remy if this is a different issue, feel free to close this one 🙂

**Comment by remy** [comment]
Is `ca.` a new cname? It might be that...

**Comment by MattiSG** [comment]
It's a new language, so yes, it is a new subdomain. I don't know how those are added usually 🙂

**Comment by remy** [comment]
That's live now - cname included 👍
