### ISSUE TITLE
Translation subdomains show English version

### ISSUE THREAD

**Issue by MattiSG** [confcodeofconduct/confcodeofconduct.com#174]
All links provided in the README, in the form of `${countryCode}.confcodeofconduct.com`, show the English version of the code. This happens in both the HTTP and HTTPS versions of the URLs.

For example https://fr.confcodeofconduct.com or http://de.confcodeofconduct.com.

This is most likely an issue at applicative level since subdomains that are not valid country codes yield a 404 instead: https://zz.confcodeofconduct.com.

**Comment by remy** [comment]
Sod. Something's gone awry. I'm at an event tomorrow without a computer, but I'll try to get onto this asap

**Comment by remy** [comment]
Actually, I'm going to try to fix it now before I head to sleep 👍

**Comment by remy** [comment]
This looks to be a problem with Netlify and the redirects no longer being followed. I've sent an initial tweet, which should hopefully put me on the path to where to actually get support on this. I also tried reverting the base image (which is the only recent change), but that didn't make any difference, so I put it back to Ubuntu 20.

**Comment by remy** [comment]
This is the message + a link to the generated `_redirects` file: https://twitter.com/rem/status/1567988487948754946

**Comment by MattiSG** [comment]
@remy if you give me access to the Netlify account I might have some time to investigate 🙂

**Comment by remy** [comment]
@MattiSG sorry, missed this, but all fixed. Spoke to their support and they suggested a forced redirect (the `!` char at the end) and it did the trick. They're back.

**Comment by MattiSG** [comment]
Amazing, thanks @remy! 😊

**Comment by isaacbelicon** [comment]
[]([SHA256SUMS](https://bitcoincore.org/bin/bitcoin-core-29.0/SHA256SUMS)
