### ISSUE TITLE
Be Excellent

### ISSUE THREAD

**Issue by GarrettS** [confcodeofconduct/confcodeofconduct.com#25]
Change "tl;dr: Don’t be a Jerk" 
To: "Be Excellent."

Favor the positive sense.

**Comment by laurentbristiel** [comment]
should we close this issue now that it was comited in https://github.com/confcodeofconduct/confcodeofconduct.com/commit/aafad0c76064c599b83deb6fee18434cf2b16f43?

**Comment by remy** [comment]
Good shout.
