### ISSUE TITLE
Automated deploy to heroku

### ISSUE THREAD

**Issue by remy** [confcodeofconduct/confcodeofconduct.com#38]
Merges to master should automatically deploy to heroku.

I know how to do this via travis-ci - but not sure if there's another, simpler (i.e. without travis) way.

Otherwise we just do `git push heroku master`. No biggie?

**Comment by MattiSG** [comment]
Changes seem to be deployed continuously, however there is no indication in the `CONTRIBUTING`, nor in the `README`, nor in dotfiles, of how this is achieved (and could thus be tweaked).

@remy your input here would be very welcome :wink:

**Comment by sh1989** [comment]
Automated deployments via Heroku can be configured via your app's dashboard. Go to the "Deploy" tab and link Heroku to this repository. This will allow you to configure auto-deployment from the master branch (whenever there's a push). There's additionally a checkbox to allow for deployment to wait until a CI build has ran.

If you ever need to, you can always perform a manual deployment from another branch.

More info: https://devcenter.heroku.com/articles/github-integration#automatic-deploys

**Comment by remy** [comment]
Yeah, it's going via Heroku continuously monitoring the git repo.

I should have closed this ages ago!
