### ISSUE TITLE
Hack Code of Conduct

### ISSUE THREAD

**Issue by cbetta** [confcodeofconduct/confcodeofconduct.com#56]
Just wanted to let you know I created http://hackcodeofconduct.org/ with some heavy inspiration from this document. Not really an issue but thought it was worth sharing and couldnt find who owned this project exactly to email.

**Comment by MattiSG** [comment]
Thanks for the heads up :wink:

Since this is an example of adapting the code of conduct to a hackathon context, this is also related to #90, #47 and #123.
