### ISSUE TITLE
Booth staff? What does it mean?

### ISSUE THREAD

**Issue by timmarinin** [confcodeofconduct/confcodeofconduct.com#60]
https://github.com/confcodeofconduct/confcodeofconduct.com/blob/master/index.html#L86

> Booth staff (including volunteers) should not use sexualised clothing/uniforms/costumes, or otherwise create a sexualised environment.

What does „booth staff” means? Is it typo and I should read it as „both staff (including volunteers)”

I'm working on russian translation.

**Comment by AlexPotor** [comment]
That is really interesting to me that this term "booth staff" is not known by everyone. We are building ExpoTor.com - if any of your exhibitors / exhibiting companies need professional and affordable booth staff ;)

**Comment by MattiSG** [comment]
@AlexPotor this comment on a 3 years old issue looks mostly like spam. I redacted the link to the advertised website.
